### PR TITLE
Typo in README.md

### PR DESCRIPTION
**Pull request by knospe-**
Minor update on README.md file.

### CODE REVIEW

**Comment by technweb** [comment]
Hi @knospe, thank you for the typo fixes. however, all commits must be signed. I will happily merge your changes if you can fix this PR. cheers!

**Comment by knospe-** [comment]
> Hi @knospe, thank you for the typo fixes. however, all commits must be signed. I will happily merge your changes if you can fix this PR. cheers!

My commit should now be signed.

**Comment by technweb** [comment]
Hi @knospe- 
Thanks, but I am still seeing the following issues:
1. `The base branch requires all commits to be signed.`
2. This pull request is sent into `master` but you should be submitting it into `develop` branch only.
3. The pull request is from an unknown repo, not sure if that matters.

**Comment by eermolaev** [comment]
all commits must be signed

**Pull request closed without merging**
